on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - name: files list
        run: ls -a
      - name: Build Docker image 
        run: docker build -t example-docker .github/example-docker/
      - name: Run tests inside the container
        id: docker-run-step
        run: docker run example-docker
      - run: echo "Time from inside the docker container (printed outside the container) is; ${{ steps.docker-run-step.outputs.time}}"
        shell: bash
