name: learn-github-actions
on: [push]
env:
  FILE_EXTENSION: bak
  SEARCH_WORD: example
  REPLACEMENT_WORD: blah
  
jobs:
  check-folder-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - run: ls -a
  run-basic-bash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
         chmod +x .github/scripts/test.sh
         .github/scripts/test.sh
        shell: bash
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
