on: [push]

jobs:
  python-hello-world-docker:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image 
        run: docker build -t python-docker .github/python-docker/
      - name: Run tests inside the container
        id: docker-run-step
        run: docker run example-docker
      - run: echo "Variable from inside the docker container (printed outside the container) is; ${{ steps.docker-run-step.outputs.variable}}"
        shell: bash
